import connectToDatabase from "@/lib/db";
import { SignOutButton } from "@clerk/nextjs";
import { currentUser } from "@clerk/nextjs/server";
import type { Metadata } from "next";
import {
  Cloud,
  CreditCard,
  Github,
  Keyboard,
  LifeBuoy,
  LogOut,
  Mail,
  MessageSquare,
  Plus,
  PlusCircle,
  Settings,
  User,
  UserPlus,
  Users,
  LayoutDashboardIcon,
  MessageCircleQuestion,
} from "lucide-react"

import { Button } from "@/components/ui/button"
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuGroup,
  DropdownMenuItem,
  DropdownMenuLabel,
  DropdownMenuPortal,
  DropdownMenuSeparator,
  DropdownMenuShortcut,
  DropdownMenuSub,
  DropdownMenuSubContent,
  DropdownMenuSubTrigger,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu"
import { fetchUser } from "@/lib/action/user.action";
import { redirect } from "next/navigation";
import Link from "next/link";
import { fetchQuiz } from "@/lib/action/quiz.action";
import Logo from "@/components/reusable/Logo";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await currentUser();
  if (!user) redirect('/sign-in');
  const db_user = await fetchUser({ clerkId: user?.id })
  if (db_user == "no-user") redirect('/onboarding');

  // await connectToDatabase();
  return (
    <div className="w-full h-screen">
      <div className="w-full h-16 flex gap-3 items-center justify-between px-10 border-b border-b-slate-100">
        <Logo href="/dashboard" />
        <DropdownMenu>
          <DropdownMenuTrigger asChild>
            <img src={db_user.user.img} className="w-8 h-8 rounded-full" />
          </DropdownMenuTrigger>
          <DropdownMenuContent className="w-56 mr-10">
            <DropdownMenuLabel>Hy {db_user.firstname},
              <br />
              <p className="text-xs text-slate-700 font-normal">@{db_user.user.username}</p>
            </DropdownMenuLabel>

            <DropdownMenuSeparator />
            <DropdownMenuGroup>
              <Link href="/dashboard">
                <DropdownMenuItem>
                  <LayoutDashboardIcon className="mr-2 h-4 w-4" />
                  <span>Dashboard</span>
                </DropdownMenuItem>
              </Link>
              <Link href={`/${db_user.user.username}`}>
                <DropdownMenuItem>
                  <User className="mr-2 h-4 w-4" />
                  <span>Profile</span>
                </DropdownMenuItem>
              </Link>
              <Link href={`/dashboard/setting`}>
                <DropdownMenuItem>
                  <Settings className="mr-2 h-4 w-4" />
                  <span>Settings</span>
                </DropdownMenuItem>
              </Link>
            </DropdownMenuGroup>
            <DropdownMenuSeparator />
            <DropdownMenuGroup>
              <Link href="/dashboard/takens">
                <DropdownMenuItem>
                  <MessageCircleQuestion className="mr-2 h-4 w-4" />
                  <span>Your Takens</span>
                </DropdownMenuItem>
              </Link>

              <Link href="/dashboard/create">
                <DropdownMenuItem>
                  <Plus className="mr-2 h-4 w-4" />
                  <span>New Quiz</span>
                </DropdownMenuItem>
              </Link>
            </DropdownMenuGroup>
            <DropdownMenuSeparator />
            <Link href="#">
              <DropdownMenuItem>
                <LifeBuoy className="mr-2 h-4 w-4" />
                <span>Support</span>
              </DropdownMenuItem>
            </Link>
            <Link href="https://github.com/MuhammadBinYasir/Quizee">
              <DropdownMenuItem>
                <Github className="mr-2 h-4 w-4" />
                <span>Rate on Github</span>
              </DropdownMenuItem>
            </Link>
            <DropdownMenuSeparator />
            <DropdownMenuItem asChild>
              <SignOutButton>
                <div className="flex">
                  <LogOut className="mr-2 h-4 w-4" />
                  <span>Log out</span>
                </div>
              </SignOutButton>
            </DropdownMenuItem>
          </DropdownMenuContent>
        </DropdownMenu>

      </div>
      {children}
    </div>
  );
}